services:
  - name: lampac-ukraine
    type: web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true

    disk:
      name: persistent
      mountPath: /persistent
      sizeGB: 1

    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:8080
