services:
  - name: lampac-ukraine
    type: web
    env: docker
    plan: free   # можеш змінити на starter для без сну
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:8080
    ports:
      - port: 8080
